apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-qj1c
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-qj1c@sha256:908cb8d14531b515650d734562e20ed31ac571be05edf101e02d5f458e4ff425
        name: my-nodejs
        resources: {}
status: {}
